workflows:
  android-workflow:
    name: Build 8K Camera APK
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Create Android project and icon
        script: |
          flutter create . --platforms=android
          flutter pub get
          dart run flutter_launcher_icons
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
