name: my_8k_camera
description: Killer Camera Top
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  gal: ^2.3.1
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0
  audioplayers: ^6.0.0

flutter:
  uses-material-design: true
